@startuml
class edu.unina.natour21.view.activity.PostCreationMapsActivity {
- {static} String TAG
- GoogleMap map
- CameraPosition cameraPosition
- LinkedList<Marker> markerLinkedList
- LinkedList<LatLng> pointLinkedList
- Polyline routePolyline
- PlacesClient placesClient
- FusedLocationProviderClient fusedLocationProviderClient
- LatLng defaultLocation
- {static} int DEFAULT_ZOOM
- {static} int PERMISSIONS_REQUEST_ACCESS_FINE_LOCATION
- boolean locationPermissionGranted
- Location lastKnownLocation
- {static} String KEY_CAMERA_POSITION
- {static} String KEY_LOCATION
- Button doneButton
- Button clearButton
# void onCreate(Bundle)
+ void onMapReady(GoogleMap)
+ void onBackPressed()
- void redrawPolyline()
- void getLocationPermission()
+ void onRequestPermissionsResult(int,String[],int[])
- void updateLocationUI()
- void getDeviceLocation()
}
class edu.unina.natour21.viewmodel.PostCreationViewModel {
+ String TAG
- MutableLiveData<Void> onUserQueryFailure
- MutableLiveData<Void> onPostQuerySuccess
- MutableLiveData<Void> onPostQueryFailure
- MutableLiveData<AuthException> onFetchUserAttributesFailure
- MutableLiveData<Void> onIncorrectFile
+ GPX generateGPXFromPointArrayList(ArrayList<LatLng>)
+ void writeGPXFile(ArrayList<LatLng>,String)
+ GPX readGPXFile(InputStream)
+ void createPost(String,String,GPX,Double,Double,String,Bitmap,Integer,Integer,Boolean)
+ void onIncorrectFile(Void)
+ LiveData<Void> getOnIncorrectFile()
+ void onUserQueryFailure(Void)
+ LiveData<Void> getOnUserQueryFailure()
+ void onPostQuerySuccess(Void)
+ LiveData<Void> getOnPostQuerySuccess()
+ void onPostQueryFailure(Void)
+ LiveData<Void> getOnPostQueryFailure()
+ void onFetchUserAttributesFailure(AuthException)
+ LiveData<AuthException> getOnFetchUserAttributesFailure()
}
class edu.unina.natour21.viewmodel.IntroductionViewModel {
}
class edu.unina.natour21.view.activity.RegistrationFormActivity {
- RegistrationFormViewModel viewModel
- DatePickerDialog datePickerDialog
- TextView registrationFormTextView
- EditText nicknameEditText
- EditText nameEditText
- EditText surnameEditText
- Button datePickerButton
- Spinner sexSpinner
- Spinner heightSpinner
- Spinner weightSpinner
- Button doneButton
- TextView errorTextView
- String email
- String formattedBirthdate
- int selectedYear
- int selectedMonth
# void onDestroy()
# void onCreate(Bundle)
- void observeViewModel()
- void initSpinners()
- void initDatePicker()
- String dateToString(int,int,int)
- String dateToFormattedString(int,int,int)
- Integer sexToInteger(String)
+ void onBackPressed()
}
class edu.unina.natour21.view.activity.GoogleLoginCallbackActivity {
# void onCreate(Bundle)
}
class edu.unina.natour21.model.Report {
- Long id
- Post post
- String title
- String description
+ Long getId()
+ void setId(Long)
+ Post getPost()
+ void setPost(Post)
+ String getTitle()
+ void setTitle(String)
+ String getDescription()
+ void setDescription(String)
}
class edu.unina.natour21.dto.UserDTO {
- {static} long serialVersionUID
- String email
- String name
- String surname
- String nickname
- String propic
- Boolean isAdmin
- Integer sex
- String birthdate
- Integer height
- Float weight
- LinkedList<PostDTO> posts
- LinkedList<UserDTO> followedUsers
+ String getEmail()
+ void setEmail(String)
+ String getName()
+ void setName(String)
+ String getSurname()
+ void setSurname(String)
+ String getNickname()
+ void setNickname(String)
+ String getPropic()
+ void setPropic(String)
+ Boolean getIsAdmin()
+ void setIsAdmin(Boolean)
+ Integer getSex()
+ void setSex(Integer)
+ String getBirthdate()
+ void setBirthdate(String)
+ Integer getHeight()
+ void setHeight(Integer)
+ Float getWeight()
+ void setWeight(Float)
+ LinkedList<PostDTO> getPosts()
+ void setPosts(LinkedList<PostDTO>)
+ LinkedList<UserDTO> getFollowedUsers()
+ void setFollowedUsers(LinkedList<UserDTO>)
+ {static} long getSerialVersionUID()
}
class edu.unina.natour21.view.activity.LogoutCallbackActivity {
# void onCreate(Bundle)
}
class edu.unina.natour21.dto.ReviewDTO {
- {static} long serialVersionUID
- Long id
- PostDTO post
- UserDTO author
- Float rate
- String description
+ {static} long getSerialVersionUID()
+ Long getId()
+ void setId(Long)
+ PostDTO getPost()
+ void setPost(PostDTO)
+ UserDTO getAuthor()
+ void setAuthor(UserDTO)
+ Float getRate()
+ void setRate(Float)
+ String getDescription()
+ void setDescription(String)
}
class edu.unina.natour21.retrofit.AmazonAPI {
+ {static} Retrofit retrofit
+ {static} Retrofit getClient()
}
class edu.unina.natour21.utility.AmplifyExceptionHandler {
+ String getStringFromAuthException(AuthException)
}
class edu.unina.natour21.utility.KeyboardHandler {
+ {static} void hideKeyboard(Activity)
}
class edu.unina.natour21.dto.ReportDTO {
- {static} long serialVersionUID
- Long id
- PostDTO post
- String title
- String description
+ Long getId()
+ void setId(Long)
+ PostDTO getPost()
+ void setPost(PostDTO)
+ String getTitle()
+ void setTitle(String)
+ String getDescription()
+ void setDescription(String)
+ {static} long getSerialVersionUID()
}
class edu.unina.natour21.utility.NatourUIDesignHandler {
+ void setFullscreen(Activity)
+ void setTextGradient(TextView)
+ void setTextGradient(Button)
+ void setTextGradientTextViewButton(TextView)
+ void setTextGradientTextViewButtonInverse(TextView)
+ void setTextGradientTextViewLeftButton(TextView)
+ void setTextGradientTextViewLeftButtonInverse(TextView)
+ void setTextGradientTextViewRightButton(TextView)
+ void setTextGradientTextViewRightButtonInverse(TextView)
}
class edu.unina.natour21.viewmodel.PostDetailsViewModel {
+ String TAG
- MutableLiveData<Void> onReportSaveSuccess
- MutableLiveData<Void> onReportSaveFailure
- MutableLiveData<Void> onUserQuerySuccess
- MutableLiveData<Void> onUserQueryFailure
- MutableLiveData<AuthException> onFetchUserAttributesFailure
- MutableLiveData<Void> onIncorrectFile
- MutableLiveData<Void> onPostQuerySuccess
- MutableLiveData<Void> onPostQueryFailure
- MutableLiveData<Void> onPostDeletionSuccess
- MutableLiveData<Void> onPostDeletionFailure
- Post currentPost
- Post editedPost
- User currentUser
+ GPX generateGPXFromPointArrayList(ArrayList<LatLng>)
+ void createReport(String,String,Post)
+ void deleteCurrentPost()
+ void updatePost(String)
+ void checkUserPermissions()
+ ArrayList<LatLng> getPointArrayListFromGPX(GPX)
+ GPX readGPXFile(InputStream)
+ void onPostDeletionSuccess()
+ void onPostDeletionFailure()
+ void onUserQuerySuccess()
+ void onUserQueryFailure()
+ void onPostQuerySuccess()
+ void onPostQueryFailure()
+ LiveData<Void> getOnPostDeletionSuccess()
+ LiveData<Void> getOnPostDeletionFailure()
+ LiveData<Void> getOnUserQueryFailure()
+ LiveData<Void> getOnPostQuerySuccess()
+ LiveData<Void> getOnPostQueryFailure()
+ void onFetchUserAttributesFailure(AuthException)
+ void onIncorrectFile()
+ LiveData<Void> getOnUserQuerySuccess()
+ LiveData<AuthException> getOnFetchUserAttributesFailure()
+ LiveData<Void> getOnReportSaveSuccess()
+ LiveData<Void> getOnReportSaveFailure()
+ LiveData<Void> getOnIncorrectFile()
+ Post getCurrentPost()
+ void setCurrentPost(Post)
+ User getCurrentUser()
+ void setCurrentUser(User)
+ Post getEditedPost()
+ void setEditedPost(Post)
}
class edu.unina.natour21.view.activity.IntroductionActivity {
- IntroductionViewModel viewModel
- AnimatedVectorDrawable moonAnimation
- ImageView moonImageView
- AnimatedVectorDrawable earthAnimation
- ImageView earthImageView
- TextView natourTextView
- Button signInButton
- ConstraintLayout planetLayout
# void onCreate(Bundle)
}
class edu.unina.natour21.view.fragment.RouteSearchFragment {
+ String TAG
- RouteExplorationViewModel viewModel
- EditText searchEditText
- TextView routesSelectorButton
- TextView usersSelectorButton
- TextView filterByButton
- ImageView searchImageViewButton
- ImageView cardsBackgroundImageView
- ImageView cardsWhiteBarImageView
- RecyclerView recyclerView
- LinearLayout linearLayout
- ImageView popupRouteFilteringBackButtonImageView
- TextView popupRouteFilteringDifficultyTextView
- TextView popupRouteFilteringDurationTextView
- TextView popupRouteFilteringGeographicAreaTextView
- TextView popupRouteFilteringAccessibilityTextView
- Slider popupRouteFilterDurationSlider
- TextView popupRouteFilteringDurationSliderValueTextView
- Button popupRouteFilteringGeographicAreaButton
- CheckBox popupRouteFilteringAccessibilityCheckBox
- ImageView popupRouteFilteringImageViewClearButton
- ImageView popupRouteFilteringImageViewDoneButton
- LinearLayout popupRouteFilteringDifficultyLinearLayout
- Dialog loadingDialog
- Boolean filterActive
- String searchedText
- Double areaStartLat
- Double areaStartLng
- Integer difficultyFilterValue
- Float durationFilterValue
- Boolean accessibilityFilterValue
- Integer currentRecyclerViewPage
- Integer recyclerViewPageSize
~ ActivityResultLauncher<Intent> PostFilteringMapActivityResultLauncher
+ {static} RouteSearchFragment newInstance()
+ void onCreate(Bundle)
+ void onViewCreated(View,Bundle)
+ void onResume()
- void observeViewModel()
+ View onCreateView(LayoutInflater,ViewGroup,Bundle)
- void searchButtonAction()
- void showFilterDialog()
- void redrawDifficultyDots(int)
- void resetFilterValues()
- void showLoadingDialog()
- void dismissLoadingDialog()
}
class edu.unina.natour21.view.activity.RouteExplorationActivity {
- Button signOutButton
- ActionBar actionBar
- BottomNavigationView navigationView
- TextView natourTextView
- TextView welcomeTextView
- ImageView createPostImageViewButton
- SharedPreferences sharedPrefs
- SharedPreferences.Editor sharedPrefsEditor
- RouteExplorationViewModel viewModel
- BottomNavigationView.OnNavigationItemSelectedListener selectedListener
# void onCreate(Bundle)
}
class edu.unina.natour21.viewmodel.ResetPasswordViewModel {
- MutableLiveData<AuthException> onPasswordChangeError
- MutableLiveData<Void> onPasswordChangeSuccess
+ boolean checkFieldsValidity(String,String,String)
+ boolean checkPasswordMatch(String,String)
+ void confirmResetPassword(String,String)
- void onPasswordResetFailure(AuthException)
- void onPasswordResetSuccess()
+ LiveData<AuthException> getPasswordChangeError()
+ LiveData<Void> getPasswordChangeSuccess()
}
class edu.unina.natour21.viewmodel.SignUpViewModel {
- MutableLiveData<AuthException> onSignUpFailure
- MutableLiveData<AuthSignUpResult> onSignUpSuccess
+ void signOut()
+ boolean checkEmailFieldValidity(String)
+ boolean checkPasswordFieldsValidity(String,String)
+ boolean checkPasswordMatch(String,String)
+ void signUp(String,String)
- void onSignUpFailure(AuthException)
- void onSignUpSuccess(AuthSignUpResult)
+ LiveData<AuthException> getOnSignUpFailure()
+ LiveData<AuthSignUpResult> getOnSignUpSuccess()
}
class edu.unina.natour21.viewmodel.RegistrationFormViewModel {
- MutableLiveData<Boolean> onSaveUser
- {static} String userEmail
- {static} void setUserEmail(String)
+ void signOut()
+ void saveNewUser(String,String,String,Integer,String,Integer,Float)
- void onSaveUser(boolean)
+ boolean checkNicknameFieldValidity(String)
+ boolean checkNameAndSurnameFieldValidity(String,String)
+ boolean checkBirthdateValidity(int,int)
+ boolean checkWeightAndHeightValidity(Integer,Float)
+ MutableLiveData<Boolean> getOnSaveUser()
}
class edu.unina.natour21.adapter.PostCardAdapter {
- Post[] localDataSet
+ ViewHolder onCreateViewHolder(ViewGroup,int)
+ void onBindViewHolder(ViewHolder,int)
+ int getItemCount()
+ void setLocalDataSet(Post[])
}
class edu.unina.natour21.adapter.PostCardAdapter.ViewHolder {
- ImageView picImageView
- ImageView reportImageView
- ImageView accessibilityImageView
- TextView titleTextView
- TextView authorTextView
- TextView durationTextView
- LinearLayout difficultyLinearLayout
- FloatingActionButton reportBackgroundButton
- FloatingActionButton accessibilityBackgroundButton
- Button rateBackgroundButton
+ ImageView getPicImageView()
+ ImageView getReportImageView()
+ ImageView getAccessibilityImageView()
+ TextView getTitleTextView()
+ TextView getAuthorTextView()
+ TextView getDurationTextView()
+ LinearLayout getDifficultyLinearLayout()
+ FloatingActionButton getReportBackgroundButton()
+ FloatingActionButton getAccessibilityBackgroundButton()
+ Button getRateBackgroundButton()
}
class edu.unina.natour21.dto.PostDTO {
- {static} long serialVersionUID
- Long id
- String title
- String description
- String timestamp
- String editTimestamp
- Boolean accessibility
- Integer duration
- Integer difficulty
- String route
- Double startLat
- Double startLng
- LinkedList<String> pics
- Boolean isReported
- Float rate
- UserDTO author
+ Long getId()
+ void setId(Long)
+ String getTitle()
+ void setTitle(String)
+ String getDescription()
+ void setDescription(String)
+ String getEditTimestamp()
+ void setEditTimestamp(String)
+ String getTimestamp()
+ void setTimestamp(String)
+ Boolean getAccessibility()
+ void setAccessibility(Boolean)
+ Integer getDuration()
+ void setDuration(Integer)
+ Integer getDifficulty()
+ void setDifficulty(Integer)
+ String getRoute()
+ void setRoute(String)
+ Double getStartLat()
+ void setStartLat(Double)
+ Double getStartLng()
+ void setStartLng(Double)
+ LinkedList<String> getPics()
+ void setPics(LinkedList<String>)
+ Boolean getIsReported()
+ void setIsReported(Boolean)
+ UserDTO getAuthor()
+ void setAuthor(UserDTO)
+ Boolean getReported()
+ void setReported(Boolean)
+ Float getRate()
+ void setRate(Float)
+ {static} long getSerialVersionUID()
}
class edu.unina.natour21.viewmodel.AuthenticationViewModel {
- MutableLiveData<AuthException> onLoginError
- MutableLiveData<AuthSignInResult> onLoginSuccess
- MutableLiveData<AuthResetPasswordResult> onResetPasswordRequestSuccess
- MutableLiveData<AuthException> onResetPasswordRequestError
- MutableLiveData<AuthSignInResult> onGoogleSignInSuccess
- MutableLiveData<AuthException> onGoogleSignInFailure
- MutableLiveData<AuthException> onCheckInfoFailure
- {static} String userEmail
- {static} void setUserEmail(String)
+ void signOut()
+ void signIn(String,String)
+ void googleSignIn(Activity)
+ void onGoogleSignInSuccess(AuthSignInResult)
+ void onGoogleSignInFailure(AuthException)
+ void sendResetPasswordRequest(String)
+ void onResetPasswordRequestSuccess(AuthResetPasswordResult)
+ void onResetPasswordRequestError(AuthException)
+ void onLoginSuccess(AuthSignInResult)
+ void onLoginError(AuthException)
+ boolean checkFieldsValidity(String,String)
+ boolean checkEmailFieldValidity(String)
+ void checkUserInfoAndRedirect(Activity)
+ LiveData<AuthException> getLoginError()
+ LiveData<AuthSignInResult> getLoginSuccess()
+ LiveData<AuthSignInResult> getGoogleLoginSuccess()
+ LiveData<AuthException> getGoogleLoginError()
+ LiveData<AuthResetPasswordResult> getResetPasswordSuccess()
+ LiveData<AuthException> getResetPasswordError()
+ MutableLiveData<AuthException> getOnCheckInfoFailure()
}
class edu.unina.natour21.model.Review {
- Long id
- Post post
- User author
- Float rate
- String description
+ Long getId()
+ void setId(Long)
+ Post getPost()
+ void setPost(Post)
+ User getAuthor()
+ void setAuthor(User)
+ Float getRate()
+ void setRate(Float)
+ String getDescription()
+ void setDescription(String)
}
interface edu.unina.natour21.retrofit.IUserAPI {
~ Call<List<UserDTO>> getUsersWithPaging(Integer,Integer,String)
~ Call<UserDTO> getUserByEmail(String)
~ Call<UserDTO> saveNewUser(UserDTO)
}
class edu.unina.natour21.utility.NatourResourceHandler {
+ BitmapDescriptor bitmapDescriptorFromVector(Context,int)
}
class edu.unina.natour21.utility.NatourFileHandler {
+ String createImageFromBitmap(Context,Bitmap)
+ void deleteFileFromFilename(Context,String)
+ Bitmap openBitmapFromFilename(Context,String)
}
class edu.unina.natour21.view.activity.ResetPasswordActivity {
- ResetPasswordViewModel viewModel
- TextView forcedResetPasswordTextView
- EditText editTextVerificationCode
- TextView errorTextView
- EditText editTextResetPassword
- EditText editTextVerifyPassword
- Button buttonDone
# void onCreate(Bundle)
- void observeViewModel()
}
class edu.unina.natour21.viewmodel.VerificationViewModel {
- MutableLiveData<String> onTimerUpdate
- MutableLiveData<Void> onTimerFinish
- MutableLiveData<AuthException> onSignUpConfirmationFailure
- MutableLiveData<AuthSignUpResult> onSignUpConfirmationSuccess
- MutableLiveData<AuthSignUpResult> onResendCodeSuccess
- MutableLiveData<AuthException> onResendCodeFailure
+ void signOut()
+ void startCodeTimer(long)
+ void resendCode(String)
- void onResendCodeSuccess(AuthSignUpResult)
- void onResendCodeFailure(AuthException)
+ void signUpConfirmation(String,String)
- void onSignUpConfirmationFailure(AuthException)
- void onSignUpConfirmationSuccess(AuthSignUpResult)
+ LiveData<AuthSignUpResult> getOnResendCodeSuccess()
+ LiveData<AuthException> getOnResendCodeFailure()
+ LiveData<AuthException> getOnSignUpConfirmationFailure()
+ LiveData<AuthSignUpResult> getOnSignUpConfirmationSuccess()
+ LiveData<String> getOnTimerUpdate()
+ LiveData<Void> getOnTimerFinish()
}
class edu.unina.natour21.adapter.UserCardAdapter {
- User[] localDataSet
+ ViewHolder onCreateViewHolder(ViewGroup,int)
+ void onBindViewHolder(ViewHolder,int)
+ int getItemCount()
+ void setLocalDataSet(User[])
}
class edu.unina.natour21.adapter.UserCardAdapter.ViewHolder {
- ImageView propicImageView
- TextView nicknameTextView
- TextView nameSurnameTextView
- ImageView followImageViewButton
+ ImageView getPropicImageView()
+ TextView getNicknameTextView()
+ TextView getNameSurnameTextView()
+ ImageView getFollowImageView()
}
class edu.unina.natour21.viewmodel.RouteExplorationViewModel {
+ String TAG
- MutableLiveData<Post[]> onPostFetchSuccess
- MutableLiveData<Post[]> onPostFetchFailure
- Post[] posts
- MutableLiveData<User[]> onUserFetchSuccess
- MutableLiveData<User[]> onUserFetchFailure
- User[] users
+ void setFragment(Fragment,FragmentTransaction)
+ void getPostByRange(Long,Long)
+ void getUsersWithPaging(Integer,Integer,String)
+ void getPostsWithPaging(Integer,Integer,String,Double,Double,Integer,Integer,Boolean)
- void onPostFetchSuccess(Post[])
- void onUserFetchSuccess(User[])
- void onPostFetchFailure(Post[])
- void onUserFetchFailure(User[])
+ LiveData<Post[]> getOnPostFetchSuccess()
+ LiveData<Post[]> getOnPostFetchFailure()
+ LiveData<User[]> getOnUserFetchSuccess()
+ LiveData<User[]> getOnUserFetchFailure()
+ void setPosts(Post[])
+ void setUsers(User[])
+ Post[] getPosts()
+ User[] getUsers()
}
class edu.unina.natour21.view.activity.PostCreationActivity {
+ String TAG
- PostCreationViewModel viewModel
- LinearLayout difficultyLinearLayout
- Slider durationSlider
- TextView durationValueTextView
- Button doneButton
- TextView otherSettingsBoxTextView
- TextView routePathTextViewButton
- TextView routeGPXTextViewButton
- EditText nameEditText
- EditText descriptionEditText
- CheckBox accessibilityCheckBox
- TextView picturesTapTextView
- ImageView picturesPreviewImageView
- ImageView picturesPreviewBackgroundImageView
- Button picturesClearButton
- ImageView backButtonImageView
- ArrayList<LatLng> pointArrayList
- Integer selectedDifficultyDotIndex
- Integer routeDurationIndex
- GPX tmpGPX
- Double startLat
- Double startLng
- Dialog loadingDialog
~ ActivityResultLauncher<Intent> PostCreationMapActivityResultLauncher
~ ActivityResultLauncher<Intent> GPXChooserActivityResultLauncher
~ ActivityResultLauncher<Intent> PictureChooserActivityResultLauncher
# void onCreate(Bundle)
- void redrawDifficultyDots(int)
- void showLoadingDialog()
- void dismissLoadingDialog()
}
class edu.unina.natour21.model.FavCollection {
- Long id
- User author
- String title
- LinkedList<Post> posts
+ Long getId()
+ void setId(Long)
+ User getAuthor()
+ void setAuthor(User)
+ String getTitle()
+ void setTitle(String)
+ LinkedList<Post> getPosts()
+ void setPosts(LinkedList<Post>)
}
class edu.unina.natour21.view.activity.SignUpActivity {
- SignUpViewModel viewModel
- Button nextButton
- TextView errorTextView
- TextView registrationFormTextView
- EditText emailEditText
- EditText passwordEditText
- EditText verifyPasswordEditText
- NatourUIDesignHandler designHandler
- SharedPreferences sharedPrefs
- SharedPreferences.Editor sharedPrefsEditor
- long currentMillis
- long endMillis
# void onCreate(Bundle)
- void observeViewModel()
- void timerInit()
+ void onBackPressed()
}
class edu.unina.natour21.view.activity.AuthenticationActivity {
- AuthenticationViewModel viewModel
- TextView signInTextView
- EditText emailEditTextView
- EditText passwordEditTextView
- Button signInButton
- Button signInWithGoogleButton
- Button registerButton
- TextView errorTextView
- TextView forgotPasswordTextView
- Dialog loadingDialog
# void onCreate(Bundle)
- void observeViewModel()
- void showLoadingDialog()
- void dismissLoadingDialog()
}
class edu.unina.natour21.model.Post {
- Long id
- String title
- String description
- Timestamp timestamp
- Timestamp editTimestamp
- Boolean accessibility
- Integer duration
- Integer difficulty
- GPX route
- Double startLat
- Double startLng
- LinkedList<Bitmap> pics
- Boolean isReported
- Float rate
- User author
+ {static} Creator<Post> CREATOR
+ Long getId()
+ void setId(Long)
+ String getTitle()
+ void setTitle(String)
+ String getDescription()
+ void setDescription(String)
+ Timestamp getEditTimestamp()
- void setEditTimestamp(Timestamp)
+ Timestamp getTimestamp()
+ void setTimestamp(Timestamp)
+ Boolean getAccessibility()
+ void setAccessibility(Boolean)
+ Integer getDuration()
+ void setDuration(Integer)
+ Integer getDifficulty()
+ void setDifficulty(Integer)
+ GPX getRoute()
+ void setRoute(GPX)
+ Double getStartLat()
+ void setStartLat(Double)
+ Double getStartLng()
+ void setStartLng(Double)
+ LinkedList<Bitmap> getPics()
+ void setPics(LinkedList<Bitmap>)
+ Boolean getReported()
+ void setReported(Boolean)
+ Float getRate()
+ void setRate(Float)
+ User getAuthor()
+ void setAuthor(User)
+ int describeContents()
+ void writeToParcel(Parcel,int)
}
interface edu.unina.natour21.retrofit.IReportAPI {
~ Call<Boolean> saveNewReport(ReportDTO)
}
class edu.unina.natour21.view.activity.VerificationActivity {
- VerificationViewModel viewModel
- EditText confirmationCodeEditText
- TextView verificationFormTextView
- TextView errorConfirmationCodeTextView
- Button resendCodeButton
- Button nextButton
- NatourUIDesignHandler designHandler
- SharedPreferences sharedPrefs
- SharedPreferences.Editor sharedPrefsEditor
- IUserAPI userAPI
- long currentMillis
- long endMillis
- String email
# void onCreate(Bundle)
- void observeViewModel()
- void sendCodeButtonInit()
+ void onBackPressed()
}
interface edu.unina.natour21.retrofit.IPostAPI {
~ Call<List<PostDTO>> getPostByRange(Long,Long)
~ Call<List<PostDTO>> getPostsWithPaging(Integer,Integer,String,Double,Double,Integer,Integer,Boolean)
~ Call<PostDTO> getPostByID(Long)
~ Call<PostDTO> saveNewPost(PostDTO)
~ Call<Void> deletePostById(Long)
}
class edu.unina.natour21.model.User {
- String email
- String name
- String surname
- String nickname
- Bitmap propic
- Boolean isAdmin
- Integer sex
- Date birthdate
- Integer height
- Float weight
- LinkedList<Post> posts
- LinkedList<User> followedUsers
+ {static} Creator<User> CREATOR
+ String getName()
+ void setName(String)
+ String getSurname()
+ void setSurname(String)
+ String getNickname()
+ void setNickname(String)
+ Bitmap getPropic()
+ void setPropic(Bitmap)
+ String getEmail()
+ Boolean getAdmin()
+ void setAdmin(Boolean)
+ Integer getSex()
+ void setSex(Integer)
+ Date getBirthdate()
+ void setBirthdate(Date)
+ Integer getHeight()
+ void setHeight(Integer)
+ Float getWeight()
+ void setWeight(Float)
+ LinkedList<Post> getPosts()
+ void setPosts(LinkedList<Post>)
+ LinkedList<User> getFollowedUsers()
+ void setFollowedUsers(LinkedList<User>)
+ int describeContents()
+ void writeToParcel(Parcel,int)
}
class edu.unina.natour21.application.NatourApplication {
- {static} User currentUser
- {static} AuthUser currentAmplifyUser
+ void onCreate()
+ {static} User getCurrentUser()
+ {static} void setCurrentUser(User)
+ {static} AuthUser getCurrentAmplifyUser()
+ {static} void setCurrentAmplifyUser(AuthUser)
}
class edu.unina.natour21.dto.FavCollectionDTO {
- {static} long serialVersionUID
- Long id
- UserDTO author
- String title
- LinkedList<PostDTO> posts
+ {static} long getSerialVersionUID()
+ Long getId()
+ void setId(Long)
+ UserDTO getAuthor()
+ void setAuthor(UserDTO)
+ String getTitle()
+ void setTitle(String)
+ LinkedList<PostDTO> getPosts()
+ void setPosts(LinkedList<PostDTO>)
}
class edu.unina.natour21.view.activity.PostDetailsActivity {
+ String TAG
- PostDetailsViewModel viewModel
- ImageView reportButtonImageView
- ImageView backButtonImageView
- ScrollView scrollView
- ImageView picImageView
- TextView titleTextView
- Button rateButton
- FloatingActionButton reportBackgroundButton
- ImageView reportImageView
- FloatingActionButton accessibilityBackgroundButton
- ImageView accessibilityImageView
- ImageView addToFavImageView
- ImageView userPropicImageView
- TextView userNicknameTextView
- TextView userNameSurnameTextView
- ImageView userFollowImageView
- ImageView editButtonImageView
- CardView routeCardView
- MapView routeMapView
- GoogleMap googleMap
- ConstraintLayout infoConstraintLayout
- TextView descriptionHeaderTextView
- TextView descriptionTextView
- LinearLayout difficultyLinearLayout
- TextView durationTextView
- TextView otherInfoHeaderTextView
- TextView accessibilityTextView
- ImageView accessibilityMarkerImageView
- ImageView popupPostReportBackButtonImageView
- EditText popupPostReportTitleEditText
- EditText popupPostReportDescriptionEditText
- ImageView popupPostReportImageViewDoneButton
- EditText popupPostUpdateTitleEditText
- EditText popupPostUpdateDescriptionEditText
- Slider popupPostUpdateDurationSlider
- TextView popupPostUpdateDurationSliderValueTextView
- LinearLayout popupPostUpdateDifficultyLinearLayout
- CheckBox popupPostUpdateAccessibilityCheckBox
- Button popupPostUpdateRouteTraceButton
- Button popupPostUpdateImportGPXButton
- Button popupPostUpdatePictureButton
- ImageView popupPostUpdateImageViewCancelButton
- ImageView popupPostUpdateImageViewDoneButton
- ImageView popupPostUpdateImageViewDeleteButton
- ImageView popupPostUpdateBackButtonImageView
- TextView creationDateTimestampTextView
- TextView editDateTextView
- TextView editDateTimestampTextView
- ImageView popupConfirmImageViewYesButton
- ImageView popupConfirmImageViewNoButton
- Dialog loadingDialog
- ArrayList<LatLng> pointArrayList
~ ActivityResultLauncher<Intent> PostCreationMapActivityResultLauncher
~ ActivityResultLauncher<Intent> GPXChooserActivityResultLauncher
~ ActivityResultLauncher<Intent> PictureChooserActivityResultLauncher
# void onCreate(Bundle)
+ void onMapsSdkInitialized(MapsInitializer.Renderer)
+ void onMapReady(GoogleMap)
- void showUpdateDialog()
- void redrawDifficultyDots(int)
- void showConfirmationDialog()
- void showReportDialog()
- void observeViewModel()
- void refreshView()
- void showLoadingDialog()
- void dismissLoadingDialog()
- void redrawPopupPostUpdateDifficultyDots(int)
}
class edu.unina.natour21.view.activity.PostFilteringMapsActivity {
- {static} String TAG
- GoogleMap map
- CameraPosition cameraPosition
- LatLng selectedPoint
- Circle areaCircle
- PlacesClient placesClient
- FusedLocationProviderClient fusedLocationProviderClient
- LatLng defaultLocation
- {static} int DEFAULT_ZOOM
- {static} int PERMISSIONS_REQUEST_ACCESS_FINE_LOCATION
- boolean locationPermissionGranted
- Location lastKnownLocation
- {static} String KEY_CAMERA_POSITION
- {static} String KEY_LOCATION
- Button doneButton
- Button clearButton
# void onCreate(Bundle)
+ void onMapReady(GoogleMap)
+ void onBackPressed()
- void redrawCircle()
- void getLocationPermission()
+ void onRequestPermissionsResult(int,String[],int[])
- void updateLocationUI()
- void getDeviceLocation()
}
class edu.unina.natour21.view.fragment.RouteExplorationFragment {
- {static} String ARG_PARAM1
- {static} String ARG_PARAM2
- EditText searchEditText
- Button takeMeButton
- RouteExplorationViewModel viewModel
+ {static} RouteExplorationFragment newInstance()
+ void onViewCreated(View,Bundle)
+ void onCreate(Bundle)
+ View onCreateView(LayoutInflater,ViewGroup,Bundle)
}

edu.unina.natour21.model.Review --> edu.unina.natour21.model.User
edu.unina.natour21.model.Review --> edu.unina.natour21.model.Post
edu.unina.natour21.model.FavCollection --> edu.unina.natour21.model.Post
edu.unina.natour21.model.FavCollection --> edu.unina.natour21.model.User
edu.unina.natour21.model.Report --> edu.unina.natour21.model.Post
edu.unina.natour21.model.User -- edu.unina.natour21.model.User
edu.unina.natour21.model.User -- edu.unina.natour21.model.Post
com.google.android.gms.maps.OnMapReadyCallback <|.. edu.unina.natour21.view.activity.PostCreationMapsActivity
androidx.appcompat.app.AppCompatActivity <|-- edu.unina.natour21.view.activity.PostCreationMapsActivity
androidx.lifecycle.ViewModel <|-- edu.unina.natour21.viewmodel.PostCreationViewModel
androidx.lifecycle.ViewModel <|-- edu.unina.natour21.viewmodel.IntroductionViewModel
androidx.appcompat.app.AppCompatActivity <|-- edu.unina.natour21.view.activity.RegistrationFormActivity
androidx.appcompat.app.AppCompatActivity <|-- edu.unina.natour21.view.activity.GoogleLoginCallbackActivity
java.io.Serializable <|.. edu.unina.natour21.dto.UserDTO
androidx.appcompat.app.AppCompatActivity <|-- edu.unina.natour21.view.activity.LogoutCallbackActivity
java.io.Serializable <|.. edu.unina.natour21.dto.ReviewDTO
java.io.Serializable <|.. edu.unina.natour21.dto.ReportDTO
androidx.lifecycle.ViewModel <|-- edu.unina.natour21.viewmodel.PostDetailsViewModel
androidx.appcompat.app.AppCompatActivity <|-- edu.unina.natour21.view.activity.IntroductionActivity
androidx.fragment.app.Fragment <|-- edu.unina.natour21.view.fragment.RouteSearchFragment
androidx.appcompat.app.AppCompatActivity <|-- edu.unina.natour21.view.activity.RouteExplorationActivity
androidx.lifecycle.ViewModel <|-- edu.unina.natour21.viewmodel.ResetPasswordViewModel
androidx.lifecycle.ViewModel <|-- edu.unina.natour21.viewmodel.SignUpViewModel
androidx.lifecycle.ViewModel <|-- edu.unina.natour21.viewmodel.RegistrationFormViewModel
edu.unina.natour21.adapter.Adapter <|-- edu.unina.natour21.adapter.PostCardAdapter
edu.unina.natour21.adapter.PostCardAdapter +.. edu.unina.natour21.adapter.PostCardAdapter.ViewHolder
edu.unina.natour21.adapter.ViewHolder <|-- edu.unina.natour21.adapter.PostCardAdapter.ViewHolder
java.io.Serializable <|.. edu.unina.natour21.dto.PostDTO
androidx.lifecycle.ViewModel <|-- edu.unina.natour21.viewmodel.AuthenticationViewModel
androidx.appcompat.app.AppCompatActivity <|-- edu.unina.natour21.view.activity.ResetPasswordActivity
androidx.lifecycle.ViewModel <|-- edu.unina.natour21.viewmodel.VerificationViewModel
edu.unina.natour21.adapter.Adapter <|-- edu.unina.natour21.adapter.UserCardAdapter
edu.unina.natour21.adapter.UserCardAdapter +.. edu.unina.natour21.adapter.UserCardAdapter.ViewHolder
edu.unina.natour21.adapter.ViewHolder <|-- edu.unina.natour21.adapter.UserCardAdapter.ViewHolder
androidx.lifecycle.ViewModel <|-- edu.unina.natour21.viewmodel.RouteExplorationViewModel
androidx.appcompat.app.AppCompatActivity <|-- edu.unina.natour21.view.activity.PostCreationActivity
androidx.appcompat.app.AppCompatActivity <|-- edu.unina.natour21.view.activity.SignUpActivity
androidx.appcompat.app.AppCompatActivity <|-- edu.unina.natour21.view.activity.AuthenticationActivity
android.os.Parcelable <|.. edu.unina.natour21.model.Post
androidx.appcompat.app.AppCompatActivity <|-- edu.unina.natour21.view.activity.VerificationActivity
android.os.Parcelable <|.. edu.unina.natour21.model.User
android.app.Application <|-- edu.unina.natour21.application.NatourApplication
java.io.Serializable <|.. edu.unina.natour21.dto.FavCollectionDTO
com.google.android.gms.maps.OnMapsSdkInitializedCallback <|.. edu.unina.natour21.view.activity.PostDetailsActivity
com.google.android.gms.maps.OnMapReadyCallback <|.. edu.unina.natour21.view.activity.PostDetailsActivity
androidx.appcompat.app.AppCompatActivity <|-- edu.unina.natour21.view.activity.PostDetailsActivity
com.google.android.gms.maps.OnMapReadyCallback <|.. edu.unina.natour21.view.activity.PostFilteringMapsActivity
androidx.appcompat.app.AppCompatActivity <|-- edu.unina.natour21.view.activity.PostFilteringMapsActivity
androidx.fragment.app.Fragment <|-- edu.unina.natour21.view.fragment.RouteExplorationFragment
@enduml